import json
from index import app
from model import db
from model.job import Job, JobSchema, Skill

with app.app_context():
    # open file generated by scraper, may change name later
    with open('trademedata.json', 'r', encoding='utf-8') as file:
        scraped_data = json.load(file)

    # start database session
    session = db.session()

    # start marshmallow with database session
    job_schema = JobSchema(session=session)

    for job_entry in scraped_data:
        try:
            # validate data using marshmallow
            job = job_schema.load(job_entry)
    
            session.add(job)

        except Exception as e:
            print(f"Error processing job: {job_entry.get('title', 'Unknown')} - {e}")
            session.rollback() # undo any changes if error occurs

    try:
        session.commit()
    except Exception as e:
        session.rollback()
        print(f"Failed to commit to the database: {e}")
    finally:
        session.close()