import json
from model import db
from model.job import Job, JobSchema, Skill

# open file generated by scraper, may change name later
with open('trademejobdata.json', 'r') as file:
    scraped_data = json.load(file)

job_schema = JobSchema()

for job_entry in scraped_data:
    try:
        job_data = job_schema.load(job_entry)
        job = Job(**job_data)
        db.session.add(job)

    except Exception as e:
        print(f"Error processing job: {job_entry.get('title', 'Unknown')} - {e}")
        db.session.rollback() #undo any changes if error occurs

try:
    db.session.commit()
except Exception as e:
    db.session.rollback()
    print(f"Failed to commit to the database: {e}")
finally:
    db.session.close()