"""Add summary_average_salary_over_time table

Revision ID: 045df53a0348
Revises: eaf7601eeb42
Create Date: 2025-10-13 16:38:24.437376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '045df53a0348'
down_revision = 'eaf7601eeb42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summary_average_salary_over_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('avg_salary', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('summary_average_salary_over_time')
    # ### end Alembic commands ###
