"""Add scrape_id to Job model

Revision ID: 0a996b34875c
Revises: 7d890b12b12a
Create Date: 2025-08-31 17:07:19.855927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a996b34875c'
down_revision = '7d890b12b12a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scrape_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('scrape_id')

    # ### end Alembic commands ###
