"""skill table edit

Revision ID: 722cb802b361
Revises: 636bf0225ed2
Create Date: 2024-08-29 13:54:41.347468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722cb802b361'
down_revision = '636bf0225ed2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.drop_column('date_list')
        batch_op.drop_column('date_end')

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_end', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date_list', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_column('date')

    # ### end Alembic commands ###
